import { normSub } from './categories'

/**
 * PLAN COMPTABLE GÉNÉRAL 2025 — référentiel officiel
 * Source : règlement ANC n°2022-06 du 4 novembre 2022 (homologué JO 30/12/2023),
 * obligatoire pour tout exercice ouvert à compter du 1er janvier 2025.
 * Généré depuis PCG_2025_Plan_Comptable_General.xlsx — NE PAS éditer à la main,
 * régénérer depuis le fichier source en cas de mise à jour du règlement.
 */
export interface PcgAccount { c: string; l: string }

export const PCG_2025: PcgAccount[] = [
  { c: '101', l: 'Capital' },
  { c: '1011', l: 'Capital souscrit – non appelé' },
  { c: '1012', l: 'Capital souscrit – appelé, non versé' },
  { c: '1013', l: 'Capital souscrit – appelé, versé' },
  { c: '10131', l: 'Capital non amorti' },
  { c: '10132', l: 'Capital amorti' },
  { c: '1018', l: 'Capital souscrit soumis à des réglementations particulières' },
  { c: '102', l: 'Fonds fiduciaires' },
  { c: '104', l: 'Primes liées au capital social' },
  { c: '1041', l: 'Primes d\'émission' },
  { c: '1042', l: 'Primes de fusion' },
  { c: '1043', l: 'Primes d\'apport' },
  { c: '1044', l: 'Primes de conversion d\'obligations en actions' },
  { c: '1045', l: 'Bons de souscription d\'actions' },
  { c: '105', l: 'Écarts de réévaluation' },
  { c: '1051', l: 'Réserve spéciale de réévaluation' },
  { c: '1052', l: 'Écart de réévaluation libre' },
  { c: '1053', l: 'Réserve de réévaluation' },
  { c: '1055', l: 'Écarts de réévaluation (autres opérations légales)' },
  { c: '1057', l: 'Autres écarts de réévaluation en France' },
  { c: '1058', l: 'Autres écarts de réévaluation à l\'Étranger' },
  { c: '106', l: 'Réserves' },
  { c: '1061', l: 'Réserve légale' },
  { c: '10611', l: 'Réserve légale proprement dite' },
  { c: '10612', l: 'Plus-values nettes à long terme' },
  { c: '1062', l: 'Réserves indisponibles' },
  { c: '1063', l: 'Réserves statutaires ou contractuelles' },
  { c: '1064', l: 'Réserves réglementées' },
  { c: '10641', l: 'Plus-values nettes à long terme' },
  { c: '10643', l: 'Réserves consécutives à l\'octroi de subventions d\'investissement' },
  { c: '10648', l: 'Autres réserves réglementées' },
  { c: '1068', l: 'Autres réserves' },
  { c: '10681', l: 'Réserve de propre assureur' },
  { c: '10688', l: 'Réserves diverses' },
  { c: '107', l: 'Écart d\'équivalence' },
  { c: '108', l: 'Compte de l\'exploitant' },
  { c: '109', l: 'Actionnaires : Capital souscrit – non appelé' },
  { c: '110', l: 'Report à nouveau (solde créditeur)' },
  { c: '119', l: 'Report à nouveau (solde débiteur)' },
  { c: '120', l: 'Résultat de l\'exercice (bénéfice)' },
  { c: '129', l: 'Résultat de l\'exercice (perte)' },
  { c: '131', l: 'Subventions d\'équipement' },
  { c: '1311', l: 'État' },
  { c: '1312', l: 'Régions' },
  { c: '1313', l: 'Départements' },
  { c: '1314', l: 'Communes' },
  { c: '1315', l: 'Collectivités publiques' },
  { c: '1316', l: 'Entreprises publiques' },
  { c: '1317', l: 'Entreprises et organismes privés' },
  { c: '1318', l: 'Autres' },
  { c: '138', l: 'Autres subventions d\'investissement' },
  { c: '139', l: 'Subventions d\'investissement inscrites au compte de résultat' },
  { c: '1391', l: 'Subventions d\'équipement virées au résultat' },
  { c: '1398', l: 'Autres subventions d\'investissement virées' },
  { c: '142', l: 'Provisions réglementées relatives aux immobilisations' },
  { c: '1423', l: 'Provisions pour reconstitution des gisements miniers et pétroliers' },
  { c: '1424', l: 'Provisions pour investissement (participation des salariés)' },
  { c: '143', l: 'Provisions réglementées relatives aux stocks' },
  { c: '1431', l: 'Hausse des prix' },
  { c: '1432', l: 'Fluctuation des cours' },
  { c: '144', l: 'Provisions réglementées relatives aux autres éléments de l\'actif' },
  { c: '145', l: 'Amortissements dérogatoires' },
  { c: '146', l: 'Provision spéciale de réévaluation' },
  { c: '147', l: 'Plus-values réinvesties' },
  { c: '148', l: 'Autres provisions réglementées' },
  { c: '151', l: 'Provisions pour risques' },
  { c: '1511', l: 'Provisions pour litiges' },
  { c: '1512', l: 'Provisions pour garanties données aux clients' },
  { c: '1513', l: 'Provisions pour pertes sur marchés à terme' },
  { c: '1514', l: 'Provisions pour amendes et pénalités' },
  { c: '1515', l: 'Provisions pour pertes de change' },
  { c: '1516', l: 'Provisions pour pertes sur contrats' },
  { c: '1518', l: 'Autres provisions pour risques' },
  { c: '153', l: 'Provisions pour pensions et obligations similaires' },
  { c: '154', l: 'Provisions pour restructurations' },
  { c: '155', l: 'Provisions pour impôts' },
  { c: '156', l: 'Provisions pour renouvellement des immobilisations (concessions)' },
  { c: '157', l: 'Provisions pour charges à répartir sur plusieurs exercices' },
  { c: '1572', l: 'Provisions pour gros entretien ou grandes révisions' },
  { c: '158', l: 'Autres provisions pour charges' },
  { c: '1581', l: 'Provisions pour remises en état' },
  { c: '161', l: 'Emprunts obligataires convertibles' },
  { c: '162', l: 'Obligations représentatives de passifs nets remis en fiducie' },
  { c: '163', l: 'Autres emprunts obligataires' },
  { c: '164', l: 'Emprunts auprès des établissements de crédit' },
  { c: '165', l: 'Dépôts et cautionnements reçus' },
  { c: '1651', l: 'Dépôts' },
  { c: '1655', l: 'Cautionnements' },
  { c: '166', l: 'Participation des salariés aux résultats' },
  { c: '1661', l: 'Comptes bloqués' },
  { c: '1662', l: 'Fonds de participation' },
  { c: '167', l: 'Emprunts et dettes assortis de conditions particulières' },
  { c: '1671', l: 'Émissions de titres participatifs' },
  { c: '1674', l: 'Avances conditionnées de l\'État' },
  { c: '1675', l: 'Emprunts participatifs' },
  { c: '168', l: 'Autres emprunts et dettes assimilées' },
  { c: '1681', l: 'Autres emprunts' },
  { c: '1685', l: 'Rentes viagères capitalisées' },
  { c: '1687', l: 'Autres dettes' },
  { c: '1688', l: 'Intérêts courus' },
  { c: '16881', l: 'Sur emprunts obligataires convertibles' },
  { c: '16883', l: 'Sur autres emprunts obligataires' },
  { c: '16884', l: 'Sur emprunts auprès des établissements de crédit' },
  { c: '16885', l: 'Sur dépôts et cautionnements reçus' },
  { c: '16886', l: 'Sur participation des salariés aux résultats' },
  { c: '16887', l: 'Sur emprunts et dettes assortis de conditions particulières' },
  { c: '16888', l: 'Sur autres emprunts et dettes assimilées' },
  { c: '169', l: 'Primes de remboursement des obligations' },
  { c: '171', l: 'Dettes rattachées à des participations (groupe)' },
  { c: '174', l: 'Dettes rattachées à des participations (hors groupe)' },
  { c: '178', l: 'Dettes rattachées à des sociétés en participation' },
  { c: '1781', l: 'Principal' },
  { c: '1788', l: 'Intérêts courus' },
  { c: '181', l: 'Comptes de liaison des établissements' },
  { c: '186', l: 'Biens et prestations de services échangés entre établissements (charges)' },
  { c: '187', l: 'Biens et prestations de services échangés entre établissements (produits)' },
  { c: '188', l: 'Comptes de liaison des sociétés en participation' },
  { c: '201', l: 'Frais d\'établissement' },
  { c: '2011', l: 'Frais de constitution' },
  { c: '2012', l: 'Frais de premier établissement' },
  { c: '20121', l: 'Frais de prospection' },
  { c: '20122', l: 'Frais de publicité' },
  { c: '2013', l: 'Frais d\'augmentation de capital et d\'opérations diverses' },
  { c: '203', l: 'Frais de recherche et de développement' },
  { c: '205', l: 'Concessions, brevets, licences, marques, logiciels, droits et valeurs similaires' },
  { c: '206', l: 'Droit au bail' },
  { c: '207', l: 'Fonds commercial' },
  { c: '208', l: 'Autres immobilisations incorporelles' },
  { c: '2081', l: 'Mali de fusion sur actifs incorporels' },
  { c: '211', l: 'Terrains' },
  { c: '2111', l: 'Terrains nus' },
  { c: '2112', l: 'Terrains aménagés' },
  { c: '2113', l: 'Sous-sols et sur-sols' },
  { c: '2114', l: 'Terrains de carrières' },
  { c: '2115', l: 'Terrains bâtis' },
  { c: '2116', l: 'Compte d\'ordre sur immobilisations' },
  { c: '212', l: 'Agencements et aménagements de terrains' },
  { c: '213', l: 'Constructions' },
  { c: '2131', l: 'Bâtiments' },
  { c: '2135', l: 'Installations générales – agencements – aménagements des constructions' },
  { c: '2138', l: 'Ouvrages d\'infrastructure' },
  { c: '21381', l: 'Voies de terre' },
  { c: '21382', l: 'Voies de fer' },
  { c: '21383', l: 'Voies d\'eau' },
  { c: '21384', l: 'Barrages' },
  { c: '21385', l: 'Pistes d\'aérodromes' },
  { c: '214', l: 'Constructions sur sol d\'autrui' },
  { c: '215', l: 'Installations techniques, matériels et outillage industriels' },
  { c: '2151', l: 'Installations complexes spécialisées' },
  { c: '2153', l: 'Installations à caractère spécifique' },
  { c: '2154', l: 'Matériel industriel' },
  { c: '2155', l: 'Outillage industriel' },
  { c: '2157', l: 'Agencements et aménagements du matériel et outillage industriels' },
  { c: '218', l: 'Autres immobilisations corporelles' },
  { c: '2181', l: 'Installations générales, agencements, aménagements divers' },
  { c: '2182', l: 'Matériel de transport' },
  { c: '2183', l: 'Matériel de bureau et matériel informatique' },
  { c: '2184', l: 'Mobilier' },
  { c: '2185', l: 'Cheptel' },
  { c: '2186', l: 'Emballages récupérables' },
  { c: '2187', l: 'Mali de fusions sur actifs corporels' },
  { c: '231', l: 'Immobilisations corporelles en cours' },
  { c: '2312', l: 'Terrains' },
  { c: '2313', l: 'Constructions' },
  { c: '2315', l: 'Installations techniques, matériel et outillage industriels' },
  { c: '2318', l: 'Autres immobilisations corporelles' },
  { c: '232', l: 'Immobilisations incorporelles en cours' },
  { c: '237', l: 'Avances et acomptes versés sur immobilisations incorporelles' },
  { c: '238', l: 'Avances et acomptes versés sur commandes d\'immobilisations corporelles' },
  { c: '2382', l: 'Terrains' },
  { c: '2383', l: 'Constructions' },
  { c: '2385', l: 'Installations techniques, matériel et outillage industriels' },
  { c: '2388', l: 'Autres immobilisations corporelles' },
  { c: '261', l: 'Titres de participation' },
  { c: '2611', l: 'Actions' },
  { c: '2618', l: 'Autres titres' },
  { c: '266', l: 'Autres formes de participation' },
  { c: '2661', l: 'Droits représentatifs d\'actifs nets remis en fiducie' },
  { c: '267', l: 'Créances rattachées à des participations' },
  { c: '2671', l: 'Créances rattachées à des participations (groupe)' },
  { c: '2674', l: 'Créances rattachées à des participations (hors groupe)' },
  { c: '2675', l: 'Versements représentatifs d\'apports non capitalisés' },
  { c: '2676', l: 'Avances consolidables' },
  { c: '2677', l: 'Autres créances rattachées à des participations' },
  { c: '2678', l: 'Intérêts courus' },
  { c: '268', l: 'Créances rattachées à des sociétés en participation' },
  { c: '2681', l: 'Principal' },
  { c: '2688', l: 'Intérêts courus' },
  { c: '269', l: 'Versements restant à effectuer sur titres de participation non libérés' },
  { c: '271', l: 'Titres immobilisés autres que TIAP (droit de propriété)' },
  { c: '2711', l: 'Actions' },
  { c: '2718', l: 'Autres titres' },
  { c: '272', l: 'Titres immobilisés (droit de créance)' },
  { c: '2721', l: 'Obligations' },
  { c: '2722', l: 'Bons' },
  { c: '273', l: 'Titres immobilisés de l\'activité de portefeuille (TIAP)' },
  { c: '274', l: 'Prêts' },
  { c: '2741', l: 'Prêts participatifs' },
  { c: '2742', l: 'Prêts aux associés' },
  { c: '2743', l: 'Prêts au personnel' },
  { c: '2748', l: 'Autres prêts' },
  { c: '275', l: 'Dépôts et cautionnements versés' },
  { c: '2751', l: 'Dépôts' },
  { c: '2755', l: 'Cautionnements' },
  { c: '276', l: 'Autres créances immobilisées' },
  { c: '2761', l: 'Créances diverses' },
  { c: '2768', l: 'Intérêts courus' },
  { c: '27682', l: 'Sur titres immobilisés (droit de créance)' },
  { c: '27684', l: 'Sur prêts' },
  { c: '27685', l: 'Sur dépôts et cautionnements' },
  { c: '27688', l: 'Sur créances diverses' },
  { c: '277', l: 'Actions propres ou parts propres' },
  { c: '2771', l: 'Actions propres ou parts propres' },
  { c: '2772', l: 'Actions propres ou parts propres en voie d\'annulation' },
  { c: '278', l: 'Mali de fusion sur actifs financiers' },
  { c: '279', l: 'Versements restant à effectuer sur titres immobilisés non libérés' },
  { c: '280', l: 'Amortissements des immobilisations incorporelles' },
  { c: '2801', l: 'Frais d\'établissement' },
  { c: '2803', l: 'Frais de recherche et de développement' },
  { c: '2805', l: 'Concessions, brevets, licences, logiciels, droits et valeurs similaires' },
  { c: '2807', l: 'Fonds commercial' },
  { c: '2808', l: 'Autres immobilisations incorporelles' },
  { c: '28081', l: 'Amortissements du mali de fusion sur actifs incorporels' },
  { c: '281', l: 'Amortissements des immobilisations corporelles' },
  { c: '2812', l: 'Agencements, aménagements de terrains' },
  { c: '2813', l: 'Constructions' },
  { c: '2814', l: 'Constructions sur sol d\'autrui' },
  { c: '2815', l: 'Installations techniques, matériel et outillage industriels' },
  { c: '2818', l: 'Autres immobilisations corporelles' },
  { c: '282', l: 'Amortissements des immobilisations mises en concession' },
  { c: '290', l: 'Dépréciations des immobilisations incorporelles' },
  { c: '2905', l: 'Marques, procédés, droits et valeurs similaires' },
  { c: '2906', l: 'Droit au bail' },
  { c: '2907', l: 'Fonds commercial' },
  { c: '2908', l: 'Autres immobilisations incorporelles' },
  { c: '291', l: 'Dépréciations des immobilisations corporelles' },
  { c: '292', l: 'Dépréciations des immobilisations mises en concession' },
  { c: '293', l: 'Dépréciations des immobilisations en cours' },
  { c: '2931', l: 'Immobilisations corporelles en cours' },
  { c: '2932', l: 'Immobilisations incorporelles en cours' },
  { c: '296', l: 'Dépréciations des participations et créances rattachées' },
  { c: '2961', l: 'Titres de participation' },
  { c: '2966', l: 'Autres formes de participation' },
  { c: '2967', l: 'Créances rattachées à des participations' },
  { c: '2968', l: 'Créances rattachées à des sociétés en participation' },
  { c: '297', l: 'Dépréciations des autres immobilisations financières' },
  { c: '2971', l: 'Titres immobilisés – droit de propriété' },
  { c: '2972', l: 'Titres immobilisés – droit de créance' },
  { c: '2973', l: 'Titres immobilisés de l\'activité de portefeuille' },
  { c: '2974', l: 'Prêts' },
  { c: '2975', l: 'Dépôts et cautionnements versés' },
  { c: '2976', l: 'Autres créances immobilisées' },
  { c: '311', l: 'Matières (ou groupe) A' },
  { c: '312', l: 'Matières (ou groupe) B' },
  { c: '317', l: 'Fournitures A, B, C, …' },
  { c: '321', l: 'Matières consommables' },
  { c: '3211', l: 'Matières (ou groupe) C' },
  { c: '3212', l: 'Matières (ou groupe) D' },
  { c: '322', l: 'Fournitures consommables' },
  { c: '3221', l: 'Combustibles' },
  { c: '3222', l: 'Produits d\'entretien' },
  { c: '3223', l: 'Fournitures d\'atelier et d\'usine' },
  { c: '3224', l: 'Fournitures de magasin' },
  { c: '3225', l: 'Fournitures de bureau' },
  { c: '326', l: 'Emballages' },
  { c: '3261', l: 'Emballages perdus' },
  { c: '3265', l: 'Emballages récupérables non identifiables' },
  { c: '3267', l: 'Emballages à usage mixte' },
  { c: '331', l: 'Produits en cours' },
  { c: '3311', l: 'Produits en cours P 1' },
  { c: '3312', l: 'Produits en cours P 2' },
  { c: '335', l: 'Travaux en cours' },
  { c: '3351', l: 'Travaux en cours T 1' },
  { c: '3352', l: 'Travaux en cours T 2' },
  { c: '341', l: 'Études en cours' },
  { c: '3411', l: 'Études en cours E 1' },
  { c: '3412', l: 'Études en cours E 2' },
  { c: '345', l: 'Prestations de services en cours' },
  { c: '3451', l: 'Prestations de services S 1' },
  { c: '3452', l: 'Prestations de services S 2' },
  { c: '351', l: 'Produits intermédiaires' },
  { c: '3511', l: 'Produits intermédiaires (ou groupe) A' },
  { c: '3512', l: 'Produits intermédiaires (ou groupe) B' },
  { c: '355', l: 'Produits finis' },
  { c: '3551', l: 'Produits finis (ou groupe) A' },
  { c: '3552', l: 'Produits finis (ou groupe) B' },
  { c: '358', l: 'Produits résiduels (ou matières de récupération)' },
  { c: '3581', l: 'Déchets' },
  { c: '3585', l: 'Rebuts' },
  { c: '3586', l: 'Matières de récupération' },
  { c: '371', l: 'Marchandises (ou groupe) A' },
  { c: '372', l: 'Marchandises (ou groupe) B' },
  { c: '391', l: 'Dépréciations des matières premières (et fournitures)' },
  { c: '3911', l: 'Matières (ou groupe) A' },
  { c: '3912', l: 'Matières (ou groupe) B' },
  { c: '3917', l: 'Fournitures A, B, C, …' },
  { c: '392', l: 'Dépréciations des autres approvisionnements' },
  { c: '393', l: 'Dépréciations des en-cours de production de biens' },
  { c: '394', l: 'Dépréciations des en-cours de production de services' },
  { c: '395', l: 'Dépréciations des stocks de produits' },
  { c: '397', l: 'Dépréciations des stocks de marchandises' },
  { c: '3971', l: 'Marchandise (ou groupe) A' },
  { c: '3972', l: 'Marchandise (ou groupe) B' },
  { c: '400', l: 'Fournisseurs et Comptes rattachés' },
  { c: '401', l: 'Fournisseurs' },
  { c: '4011', l: 'Fournisseurs – Achats de biens et prestations de services' },
  { c: '4017', l: 'Fournisseurs – Retenues de garantie' },
  { c: '403', l: 'Fournisseurs – Effets à payer' },
  { c: '404', l: 'Fournisseurs d\'immobilisations' },
  { c: '4041', l: 'Fournisseurs – Achats d\'immobilisations' },
  { c: '4047', l: 'Fournisseurs d\'immobilisations – Retenues de garantie' },
  { c: '405', l: 'Fournisseurs d\'immobilisations – Effets à payer' },
  { c: '408', l: 'Fournisseurs – Factures non parvenues' },
  { c: '4081', l: 'Fournisseurs' },
  { c: '4084', l: 'Fournisseurs d\'immobilisations' },
  { c: '4088', l: 'Fournisseurs – Intérêts courus' },
  { c: '409', l: 'Fournisseurs débiteurs' },
  { c: '4091', l: 'Fournisseurs – Avances et acomptes versés sur commandes' },
  { c: '4096', l: 'Fournisseurs – Créances pour emballages et matériel à rendre' },
  { c: '4097', l: 'Fournisseurs – Autres avoirs' },
  { c: '40971', l: 'Fournisseurs d\'exploitation' },
  { c: '40974', l: 'Fournisseurs d\'immobilisations' },
  { c: '4098', l: 'Rabais, remises, ristournes à obtenir et autres avoirs non encore reçus' },
  { c: '410', l: 'Clients et Comptes rattachés' },
  { c: '411', l: 'Clients' },
  { c: '4111', l: 'Clients – Ventes de biens ou de prestations de services' },
  { c: '4117', l: 'Clients – Retenues de garantie' },
  { c: '413', l: 'Clients – Effets à recevoir' },
  { c: '416', l: 'Clients douteux ou litigieux' },
  { c: '418', l: 'Clients – Produits non encore facturés' },
  { c: '4181', l: 'Clients – Factures à établir' },
  { c: '4188', l: 'Clients – Intérêts courus' },
  { c: '419', l: 'Clients créditeurs' },
  { c: '4191', l: 'Clients – Avances et acomptes reçus sur commandes' },
  { c: '4196', l: 'Clients – Dettes sur emballages et matériels consignés' },
  { c: '4197', l: 'Clients – Autres avoirs' },
  { c: '4198', l: 'Rabais, remises, ristournes à accorder et autres avoirs à établir' },
  { c: '421', l: 'Personnel – Rémunérations dues' },
  { c: '422', l: 'Comités d\'entreprises, d\'établissement, …' },
  { c: '424', l: 'Participation des salariés aux résultats' },
  { c: '4246', l: 'Réserve spéciale' },
  { c: '4248', l: 'Comptes courants' },
  { c: '425', l: 'Personnel – Avances et acomptes' },
  { c: '426', l: 'Personnel – Dépôts' },
  { c: '427', l: 'Personnel – Oppositions' },
  { c: '428', l: 'Personnel – Charges à payer et produits à recevoir' },
  { c: '4282', l: 'Dettes provisionnées pour congés à payer' },
  { c: '4284', l: 'Dettes provisionnées pour participation des salariés aux résultats' },
  { c: '4286', l: 'Autres charges à payer' },
  { c: '4287', l: 'Produits à recevoir' },
  { c: '431', l: 'Sécurité sociale' },
  { c: '437', l: 'Autres organismes sociaux' },
  { c: '438', l: 'Organismes sociaux – Charges à payer et produits à recevoir' },
  { c: '4382', l: 'Charges sociales sur congés à payer' },
  { c: '4386', l: 'Autres charges à payer' },
  { c: '4387', l: 'Produits à recevoir' },
  { c: '441', l: 'État – Subventions à recevoir' },
  { c: '4411', l: 'Subventions d\'investissement' },
  { c: '4417', l: 'Subventions d\'exploitation' },
  { c: '4418', l: 'Subventions d\'équilibre' },
  { c: '4419', l: 'Avances sur subventions' },
  { c: '442', l: 'État – Impôts et taxes recouvrables sur des tiers' },
  { c: '444', l: 'État – Impôts sur les bénéfices' },
  { c: '445', l: 'État – Taxes sur le chiffre d\'affaires' },
  { c: '4452', l: 'T.V.A. due intracommunautaire' },
  { c: '4455', l: 'Taxes sur le chiffre d\'affaires à décaisser' },
  { c: '44551', l: 'T.V.A. à décaisser' },
  { c: '44558', l: 'Taxes assimilées à la T.V.A.' },
  { c: '4456', l: 'Taxes sur le chiffre d\'affaires déductibles' },
  { c: '44562', l: 'T.V.A. sur immobilisations' },
  { c: '44563', l: 'T.V.A. transférée par d\'autres entreprises' },
  { c: '44566', l: 'T.V.A. sur autres biens et services' },
  { c: '44567', l: 'Crédit de T.V.A. à reporter' },
  { c: '44568', l: 'Taxes assimilées à la T.V.A. (déductibles)' },
  { c: '4457', l: 'Taxes sur le chiffre d\'affaires collectées par l\'entreprise' },
  { c: '44571', l: 'T.V.A. collectée' },
  { c: '44578', l: 'Taxes assimilées à la T.V.A. (collectées)' },
  { c: '4458', l: 'Taxes sur le chiffre d\'affaires à régulariser ou en attente' },
  { c: '44581', l: 'Acomptes – Régime simplifié d\'imposition' },
  { c: '44582', l: 'Acomptes – Régime du forfait' },
  { c: '44583', l: 'Remboursement de taxes sur le chiffre d\'affaires demandé' },
  { c: '44584', l: 'T.V.A. récupérée d\'avance' },
  { c: '44586', l: 'Taxes sur le chiffre d\'affaires sur factures non parvenues' },
  { c: '44587', l: 'Taxes sur le chiffre d\'affaires sur factures à établir' },
  { c: '446', l: 'Obligations cautionnées' },
  { c: '447', l: 'Autres impôts, taxes et versements assimilés' },
  { c: '448', l: 'État – Charges à payer et produits à recevoir' },
  { c: '4482', l: 'Charges fiscales sur congés à payer' },
  { c: '4486', l: 'Charges à payer' },
  { c: '4487', l: 'Produits à recevoir' },
  { c: '449', l: 'Quotas d\'émission à acquérir' },
  { c: '451', l: 'Groupe' },
  { c: '455', l: 'Associés – Comptes courants' },
  { c: '4551', l: 'Principal' },
  { c: '4558', l: 'Intérêts courus' },
  { c: '456', l: 'Associés – Opérations sur le capital' },
  { c: '4561', l: 'Associés – Comptes d\'apport en société' },
  { c: '4562', l: 'Apporteurs – Capital appelé, non versé' },
  { c: '4563', l: 'Associés – Versements reçus sur augmentation de capital' },
  { c: '4564', l: 'Associés – Versements anticipés' },
  { c: '4566', l: 'Actionnaires défaillants' },
  { c: '4567', l: 'Associés – Capital à rembourser' },
  { c: '457', l: 'Associés – Dividendes à payer' },
  { c: '458', l: 'Associés – Opérations faites en commun et en G.I.E.' },
  { c: '4581', l: 'Opérations courantes' },
  { c: '4588', l: 'Intérêts courus' },
  { c: '462', l: 'Créances sur cessions d\'immobilisations' },
  { c: '464', l: 'Dettes sur acquisitions de valeurs mobilières de placement' },
  { c: '465', l: 'Créances sur cessions de valeurs mobilières de placement' },
  { c: '467', l: 'Autres comptes débiteurs ou créditeurs' },
  { c: '468', l: 'Divers – Charges à payer et produits à recevoir' },
  { c: '4686', l: 'Charges à payer' },
  { c: '4687', l: 'Produits à recevoir' },
  { c: '471', l: 'Comptes d\'attente' },
  { c: '472', l: 'Comptes d\'attente' },
  { c: '473', l: 'Comptes d\'attente' },
  { c: '474', l: 'Comptes d\'attente' },
  { c: '475', l: 'Comptes d\'attente' },
  { c: '476', l: 'Différences de conversion – ACTIF' },
  { c: '4761', l: 'Diminution des créances' },
  { c: '4762', l: 'Augmentation des dettes' },
  { c: '4768', l: 'Différences compensées par couverture de change' },
  { c: '477', l: 'Différences de conversion – PASSIF' },
  { c: '4771', l: 'Augmentation des créances' },
  { c: '4772', l: 'Diminution des dettes' },
  { c: '4778', l: 'Différences compensées par couverture de change' },
  { c: '478', l: 'Autres comptes transitoires' },
  { c: '4786', l: 'Différences d\'évaluation sur instruments de trésorerie – ACTIF' },
  { c: '4787', l: 'Différences d\'évaluation sur instruments de trésorerie – PASSIF' },
  { c: '481', l: 'Charges à répartir sur plusieurs exercices' },
  { c: '4816', l: 'Frais d\'émission des emprunts' },
  { c: '486', l: 'Charges constatées d\'avance' },
  { c: '487', l: 'Produits constatés d\'avance' },
  { c: '488', l: 'Comptes de répartition périodique des charges et des produits' },
  { c: '4886', l: 'Charges' },
  { c: '4887', l: 'Produits' },
  { c: '491', l: 'Dépréciations des comptes de clients' },
  { c: '495', l: 'Dépréciations des comptes du groupe et des associés' },
  { c: '4951', l: 'Comptes du groupe' },
  { c: '4955', l: 'Comptes courants des associés' },
  { c: '4958', l: 'Opérations faites en commun et en G.I.E.' },
  { c: '496', l: 'Dépréciations des comptes de débiteurs divers' },
  { c: '4962', l: 'Créances sur cessions d\'immobilisations' },
  { c: '4965', l: 'Créances sur cessions de VMP' },
  { c: '4967', l: 'Autres comptes débiteurs' },
  { c: '501', l: 'Parts dans des entreprises liées' },
  { c: '502', l: 'Actions propres' },
  { c: '503', l: 'Actions' },
  { c: '5031', l: 'Titres cotés' },
  { c: '5035', l: 'Titres non cotés' },
  { c: '504', l: 'Autres titres conférant un droit de propriété' },
  { c: '505', l: 'Obligations et bons émis par la société et rachetés par elle' },
  { c: '506', l: 'Obligations' },
  { c: '5061', l: 'Titres cotés' },
  { c: '5065', l: 'Titres non cotés' },
  { c: '507', l: 'Bons du Trésor et bons de caisse à court terme' },
  { c: '508', l: 'Autres valeurs mobilières de placement et autres créances assimilées' },
  { c: '5081', l: 'Autres valeurs mobilières' },
  { c: '5082', l: 'Bons de souscription' },
  { c: '5088', l: 'Intérêts courus sur obligations, bons et valeurs assimilées' },
  { c: '509', l: 'Versements restant à effectuer sur VMP non libérées' },
  { c: '511', l: 'Valeurs à l\'encaissement' },
  { c: '5111', l: 'Coupons échus à l\'encaissement' },
  { c: '5112', l: 'Chèques à encaisser' },
  { c: '5113', l: 'Effets à l\'encaissement' },
  { c: '5114', l: 'Effets à l\'escompte' },
  { c: '512', l: 'Banques' },
  { c: '5121', l: 'Comptes en monnaie nationale' },
  { c: '5124', l: 'Comptes en devises' },
  { c: '514', l: 'Chèques postaux' },
  { c: '515', l: 'Caisses du Trésor et des établissements publics' },
  { c: '516', l: 'Sociétés de bourse' },
  { c: '517', l: 'Autres organismes financiers' },
  { c: '518', l: 'Intérêts courus' },
  { c: '5181', l: 'Intérêts courus à payer' },
  { c: '5188', l: 'Intérêts courus à recevoir' },
  { c: '519', l: 'Concours bancaires courants' },
  { c: '5191', l: 'Crédit de mobilisation de créances commerciales (CMCC)' },
  { c: '5193', l: 'Mobilisation de créances nées à l\'étranger' },
  { c: '5198', l: 'Intérêts courus sur concours bancaires courants' },
  { c: '531', l: 'Caisse siège social' },
  { c: '5311', l: 'Caisse en monnaie nationale' },
  { c: '5314', l: 'Caisse en devises' },
  { c: '532', l: 'Caisse succursale (ou usine) A' },
  { c: '533', l: 'Caisse succursale (ou usine) B' },
  { c: '590', l: 'Dépréciations des valeurs mobilières de placement' },
  { c: '5903', l: 'Actions' },
  { c: '5904', l: 'Autres titres conférant un droit de propriété' },
  { c: '5906', l: 'Obligations' },
  { c: '5908', l: 'Autres valeurs mobilières de placement et créances assimilées' },
  { c: '601', l: 'Achats stockés – Matières premières (et fournitures)' },
  { c: '6011', l: 'Matières (ou groupe) A' },
  { c: '6012', l: 'Matières (ou groupe) B' },
  { c: '6017', l: 'Fournitures A, B, C, …' },
  { c: '602', l: 'Achats stockés – Autres approvisionnements' },
  { c: '6021', l: 'Matières consommables' },
  { c: '6022', l: 'Fournitures consommables' },
  { c: '60221', l: 'Combustibles' },
  { c: '60222', l: 'Produits d\'entretien' },
  { c: '60223', l: 'Fournitures d\'atelier et d\'usine' },
  { c: '60224', l: 'Fournitures de magasin' },
  { c: '60225', l: 'Fournitures de bureau' },
  { c: '6026', l: 'Emballages' },
  { c: '6031', l: 'Variation des stocks de matières premières (et fournitures)' },
  { c: '6032', l: 'Variation des stocks des autres approvisionnements' },
  { c: '6037', l: 'Variation des stocks de marchandises' },
  { c: '604', l: 'Achats d\'études et prestations de services' },
  { c: '605', l: 'Achats de matériel, équipements et travaux' },
  { c: '606', l: 'Achats non stockés de matières et fournitures' },
  { c: '6061', l: 'Fournitures non stockables (eau, énergie, …)' },
  { c: '6063', l: 'Fournitures d\'entretien et de petit équipement' },
  { c: '6064', l: 'Fournitures administratives' },
  { c: '6068', l: 'Autres matières et fournitures' },
  { c: '607', l: 'Achats de marchandises' },
  { c: '6071', l: 'Marchandise (ou groupe) A' },
  { c: '6072', l: 'Marchandise (ou groupe) B' },
  { c: '608', l: 'Frais accessoires incorporés aux achats (récapitulatif)' },
  { c: '609', l: 'Rabais, remises et ristournes obtenus sur achats' },
  { c: '6091', l: 'De matières premières (et fournitures)' },
  { c: '6092', l: 'D\'autres approvisionnements stockés' },
  { c: '6094', l: 'D\'études et prestations de services' },
  { c: '6095', l: 'De matériel, équipements et travaux' },
  { c: '6096', l: 'D\'approvisionnements non stockés' },
  { c: '6097', l: 'De marchandises' },
  { c: '6098', l: 'Rabais, remises et ristournes non affectés' },
  { c: '611', l: 'Sous-traitance générale' },
  { c: '612', l: 'Redevances de crédit-bail' },
  { c: '6122', l: 'Crédit-bail mobilier' },
  { c: '6125', l: 'Crédit-bail immobilier' },
  { c: '613', l: 'Locations' },
  { c: '6132', l: 'Locations immobilières' },
  { c: '6135', l: 'Locations mobilières' },
  { c: '6136', l: 'Malis sur emballages' },
  { c: '614', l: 'Charges locatives et de copropriété' },
  { c: '615', l: 'Entretien et réparations' },
  { c: '6152', l: 'Sur biens immobiliers' },
  { c: '6155', l: 'Sur biens mobiliers' },
  { c: '6156', l: 'Maintenance' },
  { c: '616', l: 'Primes d\'assurances' },
  { c: '6161', l: 'Multirisques' },
  { c: '6162', l: 'Assurance obligatoire dommage construction' },
  { c: '6163', l: 'Assurance-transport' },
  { c: '6164', l: 'Risques d\'exploitation' },
  { c: '6165', l: 'Insolvabilité clients' },
  { c: '617', l: 'Études et recherches' },
  { c: '618', l: 'Divers (documentation, colloques, …)' },
  { c: '619', l: 'Rabais, remises et ristournes obtenus sur services extérieurs' },
  { c: '621', l: 'Personnel extérieur à l\'entreprise' },
  { c: '6211', l: 'Personnel intérimaire' },
  { c: '6214', l: 'Personnel détaché ou prêté à l\'entreprise' },
  { c: '622', l: 'Rémunérations d\'intermédiaires et honoraires' },
  { c: '6221', l: 'Commissions et courtages sur achats' },
  { c: '6222', l: 'Commissions et courtages sur ventes' },
  { c: '6224', l: 'Rémunérations des transitaires' },
  { c: '6225', l: 'Rémunérations d\'affacturage' },
  { c: '6226', l: 'Honoraires' },
  { c: '6227', l: 'Frais d\'actes et de contentieux' },
  { c: '6228', l: 'Divers' },
  { c: '623', l: 'Publicité, publications, relations publiques' },
  { c: '6231', l: 'Annonces et insertions' },
  { c: '6232', l: 'Échantillons' },
  { c: '6233', l: 'Foires et expositions' },
  { c: '6234', l: 'Cadeaux à la clientèle' },
  { c: '6235', l: 'Primes' },
  { c: '6236', l: 'Catalogues et imprimés' },
  { c: '6237', l: 'Publications' },
  { c: '6238', l: 'Divers (pourboires, dons courants, …)' },
  { c: '624', l: 'Transports de biens et transports collectifs du personnel' },
  { c: '6241', l: 'Transports sur achats' },
  { c: '6242', l: 'Transports sur ventes' },
  { c: '6243', l: 'Transports entre établissements ou chantiers' },
  { c: '6244', l: 'Transports administratifs' },
  { c: '6247', l: 'Transports collectifs du personnel' },
  { c: '6248', l: 'Divers' },
  { c: '625', l: 'Déplacements, missions et réceptions' },
  { c: '6251', l: 'Voyages et déplacements' },
  { c: '6255', l: 'Frais de déménagement' },
  { c: '6256', l: 'Missions' },
  { c: '6257', l: 'Réceptions' },
  { c: '626', l: 'Frais postaux et de télécommunications' },
  { c: '627', l: 'Services bancaires et assimilés' },
  { c: '6271', l: 'Frais sur titres (achat, vente, garde)' },
  { c: '6272', l: 'Commissions et frais sur émission d\'emprunts' },
  { c: '6275', l: 'Frais sur effets' },
  { c: '6276', l: 'Location de coffres' },
  { c: '6278', l: 'Autres frais et commissions sur prestations de services' },
  { c: '628', l: 'Divers (cotisations, recrutement, …)' },
  { c: '6281', l: 'Concours divers (cotisations, …)' },
  { c: '6284', l: 'Frais de recrutement de personnel' },
  { c: '629', l: 'Rabais, remises et ristournes obtenus sur autres services extérieurs' },
  { c: '631', l: 'Impôts, taxes et versements assimilés sur rémunérations (admin. des impôts)' },
  { c: '6311', l: 'Taxe sur les salaires' },
  { c: '6312', l: 'Taxe d\'apprentissage' },
  { c: '6313', l: 'Participation des employeurs à la formation professionnelle continue' },
  { c: '6314', l: 'Cotisation pour défaut d\'investissement obligatoire dans la construction' },
  { c: '6318', l: 'Autres' },
  { c: '633', l: 'Impôts, taxes et versements assimilés sur rémunérations (autres organismes)' },
  { c: '6331', l: 'Versement de transport' },
  { c: '6332', l: 'Allocations logement' },
  { c: '6333', l: 'Participation des employeurs à la formation professionnelle continue' },
  { c: '6334', l: 'Participation des employeurs à l\'effort de construction' },
  { c: '6335', l: 'Versements libératoires ouvrant droit à l\'exonération de la taxe d\'apprentissage' },
  { c: '6338', l: 'Autres' },
  { c: '635', l: 'Autres impôts, taxes et versements assimilés (admin. des impôts)' },
  { c: '6351', l: 'Impôts directs (sauf IS)' },
  { c: '63511', l: 'Contribution économique territoriale (CVAE et CFE)' },
  { c: '63512', l: 'Taxes foncières' },
  { c: '63513', l: 'Autres impôts locaux' },
  { c: '63514', l: 'Taxe sur les véhicules des sociétés' },
  { c: '6352', l: 'Taxes sur le chiffre d\'affaires non récupérables' },
  { c: '6353', l: 'Impôts indirects' },
  { c: '6354', l: 'Droits d\'enregistrement et de timbre' },
  { c: '63541', l: 'Droits de mutation' },
  { c: '6358', l: 'Autres droits' },
  { c: '637', l: 'Autres impôts, taxes et versements assimilés (autres organismes)' },
  { c: '6371', l: 'Contribution sociale de solidarité à la charge des sociétés' },
  { c: '6372', l: 'Taxes perçues par les organismes publics internationaux' },
  { c: '6374', l: 'Impôts et taxes exigibles à l\'Étranger' },
  { c: '6378', l: 'Taxes diverses' },
  { c: '641', l: 'Rémunérations du personnel' },
  { c: '6411', l: 'Salaires, appointements' },
  { c: '6412', l: 'Congés payés' },
  { c: '6413', l: 'Primes et gratifications' },
  { c: '6414', l: 'Indemnités et avantages divers' },
  { c: '6415', l: 'Supplément familial' },
  { c: '644', l: 'Rémunération du travail de l\'exploitant' },
  { c: '645', l: 'Charges de sécurité sociale et de prévoyance' },
  { c: '6451', l: 'Cotisations à l\'URSSAF' },
  { c: '6452', l: 'Cotisations aux mutuelles' },
  { c: '6453', l: 'Cotisations aux caisses de retraites' },
  { c: '6454', l: 'Cotisations aux ASSEDIC' },
  { c: '6458', l: 'Cotisations aux autres organismes sociaux' },
  { c: '646', l: 'Cotisations sociales personnelles de l\'exploitant' },
  { c: '647', l: 'Autres charges sociales' },
  { c: '6471', l: 'Prestations directes' },
  { c: '6472', l: 'Versements aux comités d\'entreprise et d\'établissement' },
  { c: '6473', l: 'Versements aux comités d\'hygiène et de sécurité' },
  { c: '6474', l: 'Versements aux autres œuvres sociales' },
  { c: '6475', l: 'Médecine du travail, pharmacie' },
  { c: '648', l: 'Autres charges de personnel' },
  { c: '649', l: 'Remboursements de charges de personnel' },
  { c: '651', l: 'Redevances pour concessions, brevets, licences, marques, logiciels, droits similaires' },
  { c: '6511', l: 'Redevances pour concessions, brevets, licences, marques, procédés, logiciels' },
  { c: '6516', l: 'Droits d\'auteur et de reproduction' },
  { c: '6518', l: 'Autres droits et valeurs similaires' },
  { c: '653', l: 'Jetons de présence' },
  { c: '654', l: 'Pertes sur créances irrécouvrables' },
  { c: '6541', l: 'Créances de l\'exercice' },
  { c: '6544', l: 'Créances des exercices antérieurs' },
  { c: '655', l: 'Quotes-parts de résultat sur opérations faites en commun' },
  { c: '6551', l: 'Quote-part de bénéfice transférée (comptabilité du gérant)' },
  { c: '6555', l: 'Quote-part de perte supportée (comptabilité des associés non gérants)' },
  { c: '658', l: 'Charges diverses de gestion courante' },
  { c: '661', l: 'Charges d\'intérêts' },
  { c: '6611', l: 'Intérêts des emprunts et dettes' },
  { c: '66116', l: 'Des emprunts et dettes assimilées' },
  { c: '66117', l: 'Des dettes rattachées à des participations' },
  { c: '6612', l: 'Charges de la fiducie, résultat de la période' },
  { c: '6615', l: 'Intérêts des comptes courants et des dépôts créditeurs' },
  { c: '6616', l: 'Intérêts bancaires et sur opérations de financement' },
  { c: '6617', l: 'Intérêts des obligations cautionnées' },
  { c: '6618', l: 'Intérêts des autres dettes' },
  { c: '66181', l: 'Des dettes commerciales' },
  { c: '66188', l: 'Des dettes diverses' },
  { c: '664', l: 'Pertes sur créances liées à des participations' },
  { c: '665', l: 'Escomptes accordés' },
  { c: '666', l: 'Pertes de change financières' },
  { c: '667', l: 'Charges nettes sur cessions de valeurs mobilières de placement' },
  { c: '668', l: 'Autres charges financières' },
  { c: '671', l: 'Charges exceptionnelles sur opérations de gestion' },
  { c: '6711', l: 'Pénalités sur marchés (et dédits payés sur achats et ventes)' },
  { c: '6712', l: 'Pénalités, amendes fiscales et pénales' },
  { c: '6713', l: 'Dons, libéralités' },
  { c: '6714', l: 'Créances devenues irrécouvrables dans l\'exercice' },
  { c: '6715', l: 'Subventions accordées' },
  { c: '6717', l: 'Rappel d\'impôts (autres qu\'IS)' },
  { c: '6718', l: 'Autres charges exceptionnelles sur opérations de gestion' },
  { c: '672', l: 'Charges sur exercices antérieurs (en cours d\'exercice)' },
  { c: '674', l: 'Opérations de constitution ou liquidation des fiducies' },
  { c: '6741', l: 'Opérations liées à la constitution de la fiducie' },
  { c: '6742', l: 'Opérations liées à la liquidation de la fiducie' },
  { c: '675', l: 'Valeurs comptables des éléments d\'actif cédés' },
  { c: '6751', l: 'Immobilisations incorporelles' },
  { c: '6752', l: 'Immobilisations corporelles' },
  { c: '6756', l: 'Immobilisations financières' },
  { c: '6758', l: 'Autres éléments d\'actif' },
  { c: '678', l: 'Autres charges exceptionnelles' },
  { c: '6781', l: 'Malis provenant de clauses d\'indexation' },
  { c: '6782', l: 'Lots' },
  { c: '6783', l: 'Malis provenant du rachat par l\'entreprise d\'actions et obligations émises par elle-même' },
  { c: '6788', l: 'Charges exceptionnelles diverses' },
  { c: '681', l: 'Dotations aux amortissements, dépréciations et provisions – Charges d\'exploitation' },
  { c: '6811', l: 'Dotations aux amortissements sur immobilisations incorporelles et corporelles' },
  { c: '68111', l: 'Immobilisations incorporelles' },
  { c: '68112', l: 'Immobilisations corporelles' },
  { c: '6812', l: 'Dotations aux amortissements des charges d\'exploitation à répartir' },
  { c: '6815', l: 'Dotations aux provisions d\'exploitation' },
  { c: '6816', l: 'Dotations aux dépréciations des immobilisations incorporelles et corporelles' },
  { c: '68161', l: 'Immobilisations incorporelles' },
  { c: '68162', l: 'Immobilisations corporelles' },
  { c: '6817', l: 'Dotations aux dépréciations des actifs circulants' },
  { c: '68173', l: 'Stocks et en-cours' },
  { c: '68174', l: 'Créances' },
  { c: '686', l: 'Dotations aux amortissements, dépréciations et provisions – Charges financières' },
  { c: '6861', l: 'Dotations aux amortissements des primes de remboursement des obligations' },
  { c: '6865', l: 'Dotations aux provisions financières' },
  { c: '6866', l: 'Dotations aux dépréciations des éléments financiers' },
  { c: '68662', l: 'Immobilisations financières' },
  { c: '68665', l: 'Valeurs mobilières de placement' },
  { c: '6868', l: 'Autres dotations' },
  { c: '687', l: 'Dotations aux amortissements, dépréciations et provisions – Charges exceptionnelles' },
  { c: '6871', l: 'Dotations aux amortissements exceptionnels des immobilisations' },
  { c: '6872', l: 'Dotations aux provisions réglementées (immobilisations)' },
  { c: '68725', l: 'Amortissements dérogatoires' },
  { c: '6873', l: 'Dotations aux provisions réglementées (stocks)' },
  { c: '6874', l: 'Dotations aux autres provisions réglementées' },
  { c: '6875', l: 'Dotations aux provisions exceptionnelles' },
  { c: '6876', l: 'Dotations aux dépréciations exceptionnelles' },
  { c: '691', l: 'Participation des salariés aux résultats' },
  { c: '695', l: 'Impôts sur les bénéfices' },
  { c: '6951', l: 'Impôts dus en France' },
  { c: '6952', l: 'Contribution additionnelle à l\'IS' },
  { c: '6954', l: 'Impôts dus à l\'étranger' },
  { c: '696', l: 'Suppléments d\'impôt sur les sociétés liés aux distributions' },
  { c: '698', l: 'Intégration fiscale' },
  { c: '6981', l: 'Intégration fiscale – Charges' },
  { c: '6989', l: 'Intégration fiscale – Produits' },
  { c: '699', l: 'Produits – Report en arrière des déficits' },
  { c: '701', l: 'Ventes de produits finis' },
  { c: '7011', l: 'Produits finis (ou groupe) A' },
  { c: '7012', l: 'Produits finis (ou groupe) B' },
  { c: '702', l: 'Ventes de produits intermédiaires' },
  { c: '703', l: 'Ventes de produits résiduels' },
  { c: '704', l: 'Travaux' },
  { c: '7041', l: 'Travaux de catégorie (ou activité) A' },
  { c: '7042', l: 'Travaux de catégorie (ou activité) B' },
  { c: '705', l: 'Études' },
  { c: '706', l: 'Prestations de services' },
  { c: '707', l: 'Ventes de marchandises' },
  { c: '7071', l: 'Marchandises (ou groupe) A' },
  { c: '7072', l: 'Marchandises (ou groupe) B' },
  { c: '708', l: 'Produits des activités annexes' },
  { c: '7081', l: 'Produits et services exploités dans l\'intérêt du personnel' },
  { c: '7082', l: 'Commissions et courtages' },
  { c: '7083', l: 'Locations diverses' },
  { c: '7084', l: 'Mise à disposition de personnel facturé' },
  { c: '7085', l: 'Port et frais accessoires facturés' },
  { c: '7086', l: 'Bonis sur reprises d\'emballages consignés' },
  { c: '7087', l: 'Bonifications obtenues des clients et primes sur ventes' },
  { c: '7088', l: 'Autres produits d\'activités annexes' },
  { c: '709', l: 'Rabais, remises et ristournes accordés par l\'entreprise' },
  { c: '7091', l: 'Sur ventes de produits finis' },
  { c: '7092', l: 'Sur ventes de produits intermédiaires' },
  { c: '7094', l: 'Sur travaux' },
  { c: '7095', l: 'Sur études' },
  { c: '7096', l: 'Sur prestations de services' },
  { c: '7097', l: 'Sur ventes de marchandises' },
  { c: '7098', l: 'Sur produits des activités annexes' },
  { c: '713', l: 'Variation des stocks (en-cours de production, produits)' },
  { c: '7133', l: 'Variation des en-cours de production de biens' },
  { c: '71331', l: 'Produits en cours' },
  { c: '71335', l: 'Travaux en cours' },
  { c: '7134', l: 'Variation des en-cours de production de services' },
  { c: '71341', l: 'Études en cours' },
  { c: '71345', l: 'Prestations de services en cours' },
  { c: '7135', l: 'Variation des stocks de produits' },
  { c: '71351', l: 'Produits intermédiaires' },
  { c: '71355', l: 'Produits finis' },
  { c: '71358', l: 'Produits résiduels' },
  { c: '721', l: 'Immobilisations incorporelles' },
  { c: '722', l: 'Immobilisations corporelles' },
  { c: '751', l: 'Redevances pour concessions, brevets, licences, marques, logiciels, droits similaires' },
  { c: '7511', l: 'Redevances pour concessions, brevets, licences, marques, procédés, logiciels' },
  { c: '7516', l: 'Droits d\'auteur et de reproduction' },
  { c: '7518', l: 'Autres droits et valeurs similaires' },
  { c: '752', l: 'Revenus des immeubles non affectés à des activités professionnelles' },
  { c: '753', l: 'Jetons de présence et rémunérations d\'administrateurs, gérants' },
  { c: '754', l: 'Ristournes perçues des coopératives (provenant des excédents)' },
  { c: '755', l: 'Quotes-parts de résultat sur opérations faites en commun' },
  { c: '7551', l: 'Quote-part de perte transférée (comptabilité du gérant)' },
  { c: '7555', l: 'Quote-part de bénéfice attribuée (comptabilité des associés non-gérants)' },
  { c: '758', l: 'Produits divers de gestion courante' },
  { c: '7587', l: 'Indemnités d\'assurance' },
  { c: '761', l: 'Produits de participations' },
  { c: '7611', l: 'Revenus des titres de participation' },
  { c: '7612', l: 'Produits de la fiducie, résultat de la période' },
  { c: '7616', l: 'Revenus sur autres formes de participation' },
  { c: '7617', l: 'Revenus des créances rattachées à des participations' },
  { c: '762', l: 'Produits des autres immobilisations financières' },
  { c: '7621', l: 'Revenus des titres immobilisés' },
  { c: '7626', l: 'Revenus des prêts' },
  { c: '7627', l: 'Revenus des créances immobilisées' },
  { c: '763', l: 'Revenus des autres créances' },
  { c: '7631', l: 'Revenus des créances commerciales' },
  { c: '7638', l: 'Revenus des créances diverses' },
  { c: '764', l: 'Revenus des valeurs mobilières de placement' },
  { c: '765', l: 'Escomptes obtenus' },
  { c: '766', l: 'Gains de change' },
  { c: '767', l: 'Produits nets sur cessions de valeurs mobilières de placement' },
  { c: '768', l: 'Autres produits financiers' },
  { c: '771', l: 'Produits exceptionnels sur opérations de gestion' },
  { c: '7711', l: 'Dédits et pénalités perçus sur achats et sur ventes' },
  { c: '7713', l: 'Libéralités reçues' },
  { c: '7714', l: 'Rentrées sur créances amorties' },
  { c: '7715', l: 'Subventions d\'équilibre' },
  { c: '7717', l: 'Dégrèvements d\'impôts autres qu\'IS' },
  { c: '7718', l: 'Autres produits exceptionnels sur opérations de gestion' },
  { c: '772', l: 'Produits sur exercices antérieurs (en cours d\'exercice)' },
  { c: '774', l: 'Opérations de constitution ou liquidation des fiducies' },
  { c: '7741', l: 'Opérations liées à la constitution de la fiducie' },
  { c: '7742', l: 'Opérations liées à la liquidation de la fiducie' },
  { c: '775', l: 'Produits des cessions d\'éléments d\'actif' },
  { c: '7751', l: 'Immobilisations incorporelles' },
  { c: '7752', l: 'Immobilisations corporelles' },
  { c: '7756', l: 'Immobilisations financières' },
  { c: '7758', l: 'Autres éléments d\'actif' },
  { c: '777', l: 'Quote-part des subventions d\'investissement virée au résultat de l\'exercice' },
  { c: '778', l: 'Autres produits exceptionnels' },
  { c: '7781', l: 'Bonis provenant de clauses d\'indexation' },
  { c: '7782', l: 'Lots' },
  { c: '7783', l: 'Bonis provenant du rachat par l\'entreprise d\'actions et d\'obligations' },
  { c: '7788', l: 'Produits exceptionnels divers' },
  { c: '781', l: 'Reprises sur amortissements, dépréciations et provisions (produits d\'exploitation)' },
  { c: '7811', l: 'Reprises sur amortissements des immobilisations incorporelles et corporelles' },
  { c: '78111', l: 'Immobilisations incorporelles' },
  { c: '78112', l: 'Immobilisations corporelles' },
  { c: '7815', l: 'Reprises sur provisions d\'exploitation' },
  { c: '7816', l: 'Reprises sur dépréciations des immobilisations corporelles et incorporelles' },
  { c: '78161', l: 'Immobilisations incorporelles' },
  { c: '78162', l: 'Immobilisations corporelles' },
  { c: '7817', l: 'Reprises sur dépréciations des actifs circulants' },
  { c: '78173', l: 'Stocks et en-cours' },
  { c: '78174', l: 'Créances' },
  { c: '786', l: 'Reprises sur dépréciations et provisions (produits financiers)' },
  { c: '7865', l: 'Reprises sur provisions financières' },
  { c: '7866', l: 'Reprises sur dépréciations des éléments financiers' },
  { c: '78662', l: 'Immobilisations financières' },
  { c: '78665', l: 'Valeurs mobilières de placement' },
  { c: '787', l: 'Reprises sur dépréciations et provisions (produits exceptionnels)' },
  { c: '7872', l: 'Reprises sur provisions réglementées (immobilisations)' },
  { c: '78725', l: 'Amortissements dérogatoires' },
  { c: '78726', l: 'Provision spéciale de réévaluation' },
  { c: '78727', l: 'Plus-values réinvesties' },
  { c: '7873', l: 'Reprises sur provisions réglementées (stocks)' },
  { c: '7874', l: 'Reprises sur autres provisions réglementées' },
  { c: '7875', l: 'Reprises sur provisions exceptionnelles' },
  { c: '7876', l: 'Reprises sur dépréciations exceptionnelles' },
  { c: '791', l: 'Transferts de charges d\'exploitation' },
  { c: '796', l: 'Transferts de charges financières' },
  { c: '797', l: 'Transferts de charges exceptionnelles' },
  { c: '801', l: 'Engagements donnés' },
  { c: '8011', l: 'Avals, cautions, garanties' },
  { c: '802', l: 'Engagements reçus' },
  { c: '8021', l: 'Avals, cautions, garanties reçus' },
  { c: '890', l: 'Bilan d\'ouverture' },
  { c: '891', l: 'Bilan de clôture' },
]

/** Intitulé officiel d'un compte (préfixe le plus long correspondant). */
export function pcgLabel(code: string): string | null {
  let best: PcgAccount | null = null
  for (const a of PCG_2025) {
    if (code.startsWith(a.c) && (!best || a.c.length > best.c.length)) best = a
  }
  return best?.l ?? null
}

/**
 * Suggestion de compte PCG depuis un texte libre (libellé de facture).
 * Score = nombre de mots (≥ 4 caractères) du texte présents dans l'intitulé officiel.
 * À score égal, préfère le compte le plus général (code le plus court).
 */
export function suggestFromPCG(text: string, classPrefix: string): PcgAccount | null {
  const tokens = normSub(text).split(/\s+/).filter(t => t.length >= 4)
  if (!tokens.length) return null
  let best: PcgAccount | null = null, bestScore = 0
  for (const a of PCG_2025) {
    if (!a.c.startsWith(classPrefix)) continue
    const nl = normSub(a.l)
    let s = 0
    for (const t of tokens) if (nl.includes(t)) s++
    if (s > bestScore || (s === bestScore && s > 0 && best !== null && a.c.length < best.c.length)) {
      best = a; bestScore = s
    }
  }
  return bestScore > 0 ? best : null
}
