import type { SigRow } from '@/types'

// Couleurs (références)
const G = '#10b981', O = '#f97316', T = '#14b8a6', P = '#8b5cf6',
      B = '#3b82f6', R = '#ef4444', A = '#f59e0b'

export const SIG: SigRow[] = [
  { id:'ca',           label:"CHIFFRE D'AFFAIRES NET",    accs:['706','7061','70611','707','708','7072'], type:'produit', bold:true, color:G, bg:'rgba(16,185,129,0.08)' },
  { id:'s1',           sep:true },
  { id:'hdr_negoce',   label:'ACTIVITÉ COMMERCIALE (NÉGOCE)', header:true, color:O },
  { id:'vte_mdse',     label:'Ventes de marchandises',   accs:['707','7072'], type:'produit', indent:1 },
  { id:'cout_mdse',    label:"Coût d'achat marchandises", accs:['607','6071','6087'], type:'charge', indent:1 },
  { id:'marge_comm',   label:'MARGE COMMERCIALE',         bold:true, color:O, bg:'rgba(249,115,22,0.08)' },
  { id:'s2',           sep:true },
  { id:'hdr_prod',     label:'ACTIVITÉ DE PRODUCTION',   header:true, color:T },
  { id:'prod_vendue',  label:'Production vendue',         accs:['706','7061','70611','708'], type:'produit', indent:1 },
  { id:'71335',        label:'Variation en-cours',        accs:['71335'], type:'produit', indent:1 },
  { id:'prod_exercice',label:"Production de l'exercice",  color:T },
  { id:'s2b',          sep:true },
  { id:'conso_prod',   label:'Consommations de production', accs:['601','6031','6081'], type:'charge', indent:1 },
  { id:'604',          label:'Sous-traitance (604)',       accs:['604'], type:'charge', indent:1 },
  { id:'marge_prod',   label:'MARGE SUR PRODUCTION',      bold:true, color:T, bg:'rgba(20,184,166,0.08)' },
  { id:'s3',           sep:true },
  { id:'marge',        label:'MARGE GLOBALE',             bold:true, color:P, bg:'rgba(139,92,246,0.12)' },
  { id:'s4',           sep:true },
  { id:'autres_ext',   label:'Autres charges externes',   accs:['60611','60612','60613','6063','613','6132','61551','616','6162','622','6221','6226','627','628'], type:'charge' },
  { id:'va',           label:'VALEUR AJOUTÉE',            bold:true, color:B },
  { id:'s5',           sep:true },
  { id:'personnel',    label:'Charges de personnel',      accs:['6411','6412','6413','6414','6415','6416','6417','6418','6419','645','6451','6452','6453','6456','6457','6475'], type:'charge' },
  { id:'ebe',          label:"EBE (Excédent Brut d'Exploitation)", bold:true, color:A, bg:'rgba(245,158,11,0.08)' },
  { id:'s6',           sep:true },
  { id:'amort',        label:'Dotations amortissements',  accs:['68111','68112','6811','6812','6813','6815','6816','6817','6871'], type:'charge' },
  { id:'re',           label:"RÉSULTAT D'EXPLOITATION",   bold:true, color:B, bg:'rgba(59,130,246,0.08)' },
  { id:'s7',           sep:true },
  { id:'fin',          label:'Résultat financier',        accs:['661','662','663','664','665','666','667','668','761','762','763','764','765','766','767','768'], type:'charge' },
  { id:'rc',           label:'RÉSULTAT COURANT',          bold:true, color:P },
  { id:'s8',           sep:true },
  { id:'excep',        label:'Résultat exceptionnel',     accs:['67','77'], type:'charge' },
  { id:'is',           label:'Impôt sur les sociétés',    accs:['695','696','697','698','699'], type:'charge' },
  { id:'rnet',         label:'RÉSULTAT NET',              bold:true, color:R, bg:'rgba(239,68,68,0.06)' },
]

export const CR: SigRow[] = [
  { id:'hdr_exp',    label:'PRODUITS',                    header:true, color:G },
  { id:'ca_v',       label:"Chiffre d'affaires ventes",   accs:['707','7061','70611','7072'], type:'produit' },
  { id:'ca_p',       label:'Chiffre d\'affaires services', accs:['706'], type:'produit' },
  { id:'ca_a',       label:'Activités annexes',           accs:['708','7080'], type:'produit' },
  { id:'sub_exp',    label:'Subventions exploitation',    accs:['74'], type:'produit' },
  { id:'autr_prod',  label:'Autres produits',             accs:['75','781','791'], type:'produit' },
  { id:'s_prod',     sep:true },
  { id:'hdr_ch',     label:'CHARGES',                    header:true, color:R },
  { id:'achat_mdse', label:'Achats marchandises',         accs:['607','6071','6087','6097'], type:'charge' },
  { id:'achat_mp',   label:'Achats mat. premières',       accs:['601','6031','6081'], type:'charge' },
  { id:'soustr',     label:'Sous-traitance',              accs:['604'], type:'charge' },
  { id:'serv_ext',   label:'Services extérieurs',         accs:['61','62'], type:'charge' },
  { id:'impots',     label:'Impôts & taxes',              accs:['63'], type:'charge' },
  { id:'sal',        label:'Salaires & traitements',      accs:['641','642'], type:'charge' },
  { id:'cs',         label:'Charges sociales',            accs:['645','646'], type:'charge' },
  { id:'amor',       label:'Dotations amortissements',    accs:['681'], type:'charge' },
  { id:'autr_ch',    label:'Autres charges',              accs:['65','66','67'], type:'charge' },
  { id:'is_cr',      label:'Impôt sur les sociétés',      accs:['695'], type:'charge' },
  { id:'s_ch',       sep:true },
  { id:'rnet_cr',    label:'RÉSULTAT NET',                bold:true, color:G, bg:'rgba(16,185,129,0.08)' },
]

export const EQ: SigRow[] = [
  { id:'hdr_eq_a',   label:'ACTIF ÉCONOMIQUE',            header:true, color:B },
  { id:'immo',       label:'Immobilisations nettes',      accs:['20','21','22','23','26','27'], type:'produit' },
  { id:'stocks',     label:'Stocks',                      accs:['31','32','33','34','35','36','37','38'], type:'produit' },
  { id:'clients_eq', label:'Créances clients',            accs:['411','412','413','416'], type:'produit' },
  { id:'autr_act',   label:'Autres actifs circulants',    accs:['40','41','42','43','44','45','46','48','5'], type:'produit' },
  { id:'eq_a',       label:"TOTAL ACTIF ÉCONOMIQUE",      bold:true, color:B },
  { id:'s_eq1',      sep:true },
  { id:'hdr_eq_p',   label:'FINANCEMENT',                 header:true, color:P },
  { id:'cap_prop',   label:'Capitaux propres',            accs:['10','11','12','13','14','15'], type:'charge' },
  { id:'det_fin',    label:'Dettes financières',          accs:['16'], type:'charge' },
  { id:'fournisseurs_eq', label:'Dettes fournisseurs',   accs:['401','402','403','404','405'], type:'charge' },
  { id:'autr_pass',  label:'Autres passifs',              accs:['42','43','44','45','46','48'], type:'charge' },
  { id:'eq_p',       label:'TOTAL FINANCEMENT',           bold:true, color:P },
  { id:'s_eq2',      sep:true },
  { id:'eq_achats',  label:'Achats (pour BFR)',           accs:['607','601','604','6071'], type:'charge' },
]
